default_language_version:
  python: python3

repos:
  - repo: local
    hooks:
      # Prevent committing .rej files
      - id: forbidden-files
        name: Forbidden files
        entry: Found Copier update rejection files; review them and remove them
        language: fail
        files: \.rej$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-merge-conflict
        args: [--assume-in-merge]

  - repo: https://github.com/myint/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        name: Format docstrings
        args:
          - --in-place
          - --wrap-summaries=88
          - --wrap-descriptions=88

  - repo: https://github.com/lyz-code/yamlfix/
    rev: 1.16.0
    hooks:
      - id: yamlfix
        name: Fix YAML
        exclude: docker-compose.*

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        name: Lint shell scripts

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        name: Format markdown
        args: [--number]
        additional_dependencies:
          - mdformat-gfm
          - mdformat-tables
          - mdformat_frontmatter
          - mdformat-toc

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        args: [--line-length=119]
        exclude: docs/source

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.5
    hooks:
      - id: ruff
        name: Check and fix with Ruff
        args:
          - --fix
      - id: ruff-format
        name: Format with Ruff

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        name: Check word spelling
        additional_dependencies:
          - tomli

  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        name: Clear notebook cells

  # jupyter notebook linting
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-ruff
        name: Format notebooks with Ruff
        args: [--line-length=119]

  - repo: https://github.com/pdm-project/pdm
    rev: 2.15.1
    hooks:
      - id: pdm-lock-check
        name: Check that pdm.lock is up to date
